baseURL = "https://www.paarc.info/"
languageCode = "en-us"
title = "PAARC"
theme = "minimal-master"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    #author = ""
    description = "The Physics and Astronomy Anti-Racism Coalition (PAARC) is a collective of physicists and astronomers dedicated to confronting and dismantling racist structures in academia."
    #githubUsername = ""
    accent = "red"
    accent2 = "lightgrey"
    profilePic = "PAARC_logo.png"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/mission/"
    name = "Mission"
    weight = 2

[[menu.main]]
    url = "/statements/"
    name = "Statements"
    weight = 3

#[[menu.main]]
#    url = "/Resources/"
#    name = "Resources"
#    weight = 4

#[[menu.main]]
#    url = "/news/"
#    name = "News"
#    weight = 5

[[menu.main]]
    url = "/events/"
    name = "Events"
    weight = 6

[[menu.main]]
    url = "/join/"
    name = "Join"
    weight = 7

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:paarcoalition@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/paarc/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/physicsastroarc/"
    name = "twitter"
    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://twitter.com/physicsastroarc"
#    name = "stack-overflow"
#    weight = 5
